apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-engagement-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-commerce-engagement-model  # Make sure this matches the template labels
  template:
    metadata:
      labels:
        app: e-commerce-engagement-model
    spec:
      containers:
      - name: e-commerce-engagement-model
        image: e-commerce-engagement-model:latest 
        imagePullPolicy: IfNotPresent  # to solve READY 0/1 status (error) of kubectl get pods command 
        ports:
        - containerPort: 8501
# Note: apply with command: kubectl apply -f deployment.yaml
