apiVersion: v1
kind: Service
metadata:
  name: e-commerce-engagement-model
spec:
  type: NodePort 
  selector:
    app: e-commerce-engagement-model
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30007  # NodePort range: 30000-32767
  externalIPs: 
    - 192.168.68.100