apiVersion: v1
kind: Service
metadata:
  name: tf-serving-engagement-model
spec:
  selector:
    app: tf-serving-engagement-model
  ports:
    - name: grpc
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: rest
      protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
