apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-serving-engagement-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-serving-engagement-model
  template:
    metadata:
      labels:
        app: tf-serving-engagement-model
    spec:
      containers:
        - name: tf-serving-engagement-model
          image: 734800375959.dkr.ecr.ap-southeast-3.amazonaws.com/e-commerce-engagement-model:latest
          ports:
            - containerPort: 8501
      imagePullSecrets:
        - name: ecr-secret
